int enterNumberInt();
float enterNumberFloat();
float calcSurfaceCircle(float a);
float calcAreaCircle(float a);
void printcalcDaysToSeconds(int tage);
void printcalcSecondsToDays(int sekunden);
void printCompareNumbers(float a, float b);
void printSmallestNumber(int a, int b, int c);
void printBiggestNumber(int a, int b, int c);
void printweekday(int tagNummer);
void printNum1to25();
void printNumXtoY_1(int x, int y);
void printNumXtoY_2(int x, int y);
void printNumXtoY_3(int x, int y);
void printRectangleStars1(int k);
void printRectangleStars2(int k);
void printRectangleStars3(int k);
void scanPrintSmallestBiggestNumber();
int calculateDivisions(int zahl, int k);
void printMultiplicationFromTO(int x, int y);
void printFakultaet(int n);
void printFakultaet_rek(int n);
void printFibonacci(int n);
int fibo(int n);
float multiply(float zahl1, float zahl2);
float divide(float zahl1, float zahl2);
float substract(float zahl1, float zahl2);
float add(float zahl1, float zahl2);
int ggt_rek(int a, int b);